export enum CollectionActionTypes {
  FILTER_BY_LOWER_PRICE = "FILTER_BY_LOWER_PRICE",
  FILTER_BY_HIGHER_PRICE = "FILTER_BY_HIGHER_PRICE",
  FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE",
}
